# Generated by Django 4.0.1 on 2024-12-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
                ('type_de_participation', models.CharField(choices=[('En présentiel', 'En présentiel'), ('Virtuelle', 'Virtuelle')], default='En présentiel', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('informations_supplémentaires', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
